const table = [
  {"id":1,"vaccine_center_name":"La Prairie, Inc.","date_of_order":"10/10/2020","Status":false,"Destination":"51178 Eagan Drive"},
  {"id":2,"vaccine_center_name":"REMEDYREPACK INC.","date_of_order":"6/14/2021","Status":false,"Destination":"1 Bartelt Alley"},
  {"id":3,"vaccine_center_name":"L'Oreal USA Products Inc","date_of_order":"10/14/2020","Status":false,"Destination":"802 Meadow Ridge Parkway"},
  {"id":4,"vaccine_center_name":"Taro Pharmaceuticals U.S.A., Inc.","date_of_order":"7/30/2020","Status":true,"Destination":"4 Atwood Avenue"},
  {"id":5,"vaccine_center_name":"Northwind Pharmaceuticals, LLC","date_of_order":"2/25/2021","Status":true,"Destination":"9692 Sunfield Park"},
  {"id":6,"vaccine_center_name":"Melaleuca Inc.","date_of_order":"8/3/2020","Status":true,"Destination":"49 Prairie Rose Center"},
  {"id":7,"vaccine_center_name":"VIATREXX BIO INCORPORATED","date_of_order":"6/5/2020","Status":true,"Destination":"5592 Vidon Parkway"},
  {"id":8,"vaccine_center_name":"Cardinal Health","date_of_order":"2/19/2021","Status":true,"Destination":"742 Banding Trail"},
  {"id":9,"vaccine_center_name":"Parfums Christian Dior","date_of_order":"5/18/2021","Status":true,"Destination":"1271 Arkansas Way"},
  {"id":10,"vaccine_center_name":"Hospira, Inc.","date_of_order":"3/4/2021","Status":true,"Destination":"951 Menomonie Road"},
  {"id":11,"vaccine_center_name":"Clinical Solutions Wholesale","date_of_order":"8/14/2021","Status":true,"Destination":"63 Swallow Trail"},
  {"id":12,"vaccine_center_name":"Cephalon, Inc.","date_of_order":"4/24/2020","Status":true,"Destination":"42 Kennedy Crossing"},
  {"id":13,"vaccine_center_name":"Physicians Total Care, Inc.","date_of_order":"9/20/2021","Status":false,"Destination":"34903 2nd Lane"},
  {"id":14,"vaccine_center_name":"Med-Health Pharma, LLC","date_of_order":"12/6/2021","Status":true,"Destination":"0 Clove Plaza"},
  {"id":15,"vaccine_center_name":"Major Pharmaceuticals","date_of_order":"9/2/2020","Status":false,"Destination":"02 Mariners Cove Street"},
  {"id":16,"vaccine_center_name":"Parfums Christian Dior","date_of_order":"6/29/2020","Status":true,"Destination":"621 Cherokee Avenue"},
  {"id":17,"vaccine_center_name":"Neutrogena Corporation","date_of_order":"7/30/2021","Status":false,"Destination":"9897 Buena Vista Parkway"},
  {"id":18,"vaccine_center_name":"Apotex Corp.","date_of_order":"6/3/2021","Status":true,"Destination":"0 Kenwood Drive"},
  {"id":19,"vaccine_center_name":"Home Sweet Homeopathics","date_of_order":"6/7/2020","Status":true,"Destination":"8926 Oak Parkway"},
  {"id":20,"vaccine_center_name":"BioActive Nutritional, Inc.","date_of_order":"7/8/2021","Status":true,"Destination":"4 Cascade Pass"},
  {"id":21,"vaccine_center_name":"A-S Medication Solutions LLC","date_of_order":"5/10/2020","Status":false,"Destination":"37684 Transport Drive"},
  {"id":22,"vaccine_center_name":"HOMEOLAB USA INC.","date_of_order":"11/5/2021","Status":true,"Destination":"3264 Dovetail Street"},
  {"id":23,"vaccine_center_name":"Uriel Pharmacy Inc.","date_of_order":"11/25/2021","Status":false,"Destination":"19 Northwestern Crossing"},
  {"id":24,"vaccine_center_name":"Northwind Pharmaceuticals, LLC","date_of_order":"7/7/2021","Status":false,"Destination":"87 Monument Drive"},
  {"id":25,"vaccine_center_name":"Ventura Corporation LTD.","date_of_order":"1/18/2021","Status":true,"Destination":"8178 Kedzie Drive"},
  {"id":26,"vaccine_center_name":"Cardinal Health","date_of_order":"3/31/2020","Status":true,"Destination":"2 Green Ridge Circle"},
  {"id":27,"vaccine_center_name":"Sandoz,Inc.","date_of_order":"11/15/2021","Status":false,"Destination":"029 Holmberg Park"},
  {"id":28,"vaccine_center_name":"Reckitt Benckiser LLC","date_of_order":"9/19/2021","Status":true,"Destination":"596 Erie Alley"},
  {"id":29,"vaccine_center_name":"Cardinal Health","date_of_order":"10/9/2021","Status":false,"Destination":"757 Village Green Road"},
  {"id":30,"vaccine_center_name":"Meijer Distribution Inc","date_of_order":"10/2/2020","Status":false,"Destination":"3 Porter Crossing"},
  {"id":31,"vaccine_center_name":"REMEDYREPACK INC.","date_of_order":"6/17/2020","Status":true,"Destination":"87 International Court"},
  {"id":32,"vaccine_center_name":"Physicians Total Care, Inc.","date_of_order":"12/17/2020","Status":false,"Destination":"832 Carioca Pass"},
  {"id":33,"vaccine_center_name":"PUREMEDY","date_of_order":"11/26/2021","Status":false,"Destination":"4080 Forest Circle"},
  {"id":34,"vaccine_center_name":"Dolgencorp Inc","date_of_order":"8/19/2021","Status":true,"Destination":"811 Anhalt Court"},
  {"id":35,"vaccine_center_name":"Publix Super Markets Inc","date_of_order":"10/10/2021","Status":false,"Destination":"18 Judy Street"},
  {"id":36,"vaccine_center_name":"Geiss, Destin & Dunn, Inc (Goodsense)","date_of_order":"10/10/2021","Status":false,"Destination":"8 Pepper Wood Plaza"},
  {"id":37,"vaccine_center_name":"McKesson Contract Packaging","date_of_order":"7/6/2021","Status":false,"Destination":"9 Waubesa Court"},
  {"id":38,"vaccine_center_name":"Newton Laboratories, Inc.","date_of_order":"8/8/2021","Status":false,"Destination":"62944 Rowland Hill"},
  {"id":39,"vaccine_center_name":"LG Household and Healthcare, Inc.","date_of_order":"3/14/2021","Status":false,"Destination":"0 Myrtle Alley"},
  {"id":40,"vaccine_center_name":"White Manufacturing Inc. DBA Micro-West","date_of_order":"6/2/2020","Status":false,"Destination":"6668 Mosinee Trail"},
  {"id":41,"vaccine_center_name":"TOP CARE (Topco Associates LLC)","date_of_order":"8/7/2021","Status":true,"Destination":"09 Sunnyside Center"},
  {"id":42,"vaccine_center_name":"HOMEOLAB USA INC","date_of_order":"3/11/2021","Status":true,"Destination":"82 Basil Center"},
  {"id":43,"vaccine_center_name":"H.J. Harkins Company, Inc.","date_of_order":"7/8/2020","Status":true,"Destination":"0 Maple Terrace"},
  {"id":44,"vaccine_center_name":"Wal-Mart Stores Inc","date_of_order":"10/24/2020","Status":false,"Destination":"1215 Eggendart Way"},
  {"id":45,"vaccine_center_name":"Dr.Reddy's Laboratories Inc","date_of_order":"7/30/2021","Status":true,"Destination":"22194 Hanson Road"},
  {"id":46,"vaccine_center_name":"KIK Custom Products","date_of_order":"6/19/2021","Status":false,"Destination":"0056 Jackson Trail"},
  {"id":47,"vaccine_center_name":"Your Military Exchange","date_of_order":"7/6/2021","Status":false,"Destination":"73 Sugar Street"},
  {"id":48,"vaccine_center_name":"Blenheim Pharmacal, Inc.","date_of_order":"7/5/2021","Status":true,"Destination":"9 Park Meadow Street"},
  {"id":49,"vaccine_center_name":"MSD Consumer Care, Inc.","date_of_order":"6/28/2020","Status":true,"Destination":"28 Everett Trail"},
  {"id":50,"vaccine_center_name":"Blenheim Pharmacal, Inc.","date_of_order":"12/3/2020","Status":false,"Destination":"413 Johnson Avenue"}
]

export default table